### ISSUE TITLE
ios10 - Missing parameters in info.plist 

### ISSUE THREAD

**Issue by 80leaves** [dariosalvi78/cordova-plugin-health#15]
Not quite sure where exactly it belongs into, but as of iOS 10 following two parameters have to be present in the info.plist

https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW48

NSHealthShareUsageDescription="A very good reason why I want to read your data."; 
NSHealthUpdateUsageDescription="A very good reason why I want to write data.";

80leaves

p.s. also opened up the same issue in HealthKit project
https://github.com/Telerik-Verified-Plugins/HealthKit/issues/77

**Comment by dariosalvi78** [comment]
thanks for the suggestion.
There is a way for cordova to modify the plist file, see [this](http://stackoverflow.com/questions/22769111/add-entry-to-ios-plist-file-via-cordova-config-xml). I particularly like the last idea, because, with a generic script, I could read the two sentences from a separate file that the user should specify (in some fixed position).

I welcome ideas to this regard.
