### ISSUE TITLE
How to add new data types?

### ISSUE THREAD

**Issue by phiasco12** [dariosalvi78/cordova-plugin-health#154]
Hello,

I need to add new datatype to this plugin for my project.

Could someone please let me know how i could do this?

in particular, i will need to add iOS mindful minutes as a data type.

**Comment by dariosalvi78** [comment]
if it's iOS the easiest thing to do is to use Telerik's plugin, which is exposed here.
See API [here](https://github.com/EddyVerbruggen/HealthKit).
If you want to modify the plugin, adding new data types is relatively easy, but you need to be able to understand JS, Java and probably Objective C (depending on the case). I can't really guide on this because it's really a case-by-case thing and the code is not very modular at the moment, so there are no generalised rules rather than "go and read the source".

**Comment by phiasco12** [comment]
Thanks.

been spending the last two days trying to figure this out to no avail.

All i need is to be able to add read and write permission to` HKWorkoutActivityTypeMindAndBody` data type.

**Comment by dariosalvi78** [comment]
workouts are already supported. See the activity data type.
