### ISSUE TITLE
Use workout in Google Fit to only retrieve TYPE_ACTIVITY_SEGMENT without distance and calories

### ISSUE THREAD

**Issue by sanctus671** [dariosalvi78/cordova-plugin-health#171]
First of all, appreciate all of the work on this plugin. It's working great. 

I'm using the plugin to track weight training sessions. This falls under the Activity type with the ActivityUnit set as "weightlifting". The only fields I need other than this, is the start and end date & time. When I went to update my app in Google Play, there are several new permissions added that I do not need. These are:
android.permission.ACCESS_COARSE_LOCATION, 
android.permission.ACCESS_FINE_LOCATION, 
android.permission.BODY_SENSORS, com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE

The location ones in particular are not a good look to be requesting. I'd ideally not want to be requesting these permissions since I don't need them. In fact, all of these I don't need. 

**Is there any way I can remove these permissions and bypass requesting the users location when I request authorization for the user?** 

I've tried to modify the plugin myself and remove the permissions from the plugin.xml, as well as bypassing the requestDynamicPermissions() function. When I do this however, I get the Google authorization screen, but when I select my Google account I always get the error: "user cancelled the dialog". 

Any help would be greatly appreciated!

**Comment by dariosalvi78** [comment]
this plugin does not expose Google Fit API as it is, its purpose is to abstract both Google Fit and HealthKit under the same API. This of course comes with the cost that datatypes need to be made similar between the two systems.

ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION are used to report the distance in the activities, these are added to the query in order to mimic what happens in HealthKit.

BODY_SENSORS is needed if you need one of the following: height, weight, heart_rate, fat_percentage

com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE does not depend on this plugin, see [this](https://issuetracker.google.com/issues/78380811#comment22).

Possible solution: use the "workout" data type that is currently used, only for HealthKit and make it a pure TYPE_ACTIVITY_SEGMENT without any additional distance and calories. This requires some work, I am not sure if and when I could work on it, but I will be happy to merge a PR if anybody wants to give it a try.

**Comment by dariosalvi78** [comment]
location is not required to access activity any longer
