### ISSUE TITLE
Fit not updating data frequently enough

### ISSUE THREAD

**Issue by alindzon** [dariosalvi78/cordova-plugin-health#176]
Have you considered adding subscriptions to your plugin to allow us to request the data be reasonably current?

I believe the info is here on how to do it, and it does not look complicated.

https://developers.google.com/fit/android/record for subscriptions
or even better
https://developers.google.com/fit/android/sensors for real time data

To be useful we need to be able to retrieve data that is predictably current, i.e. within X minutes.

If this can be solved, happy to make a donation!

**Comment by dariosalvi78** [comment]
that API is used by apps that record data. To receive frequent updates from sensors, then the docs say:

> If you also want to show the data in your app in real time, you need to use the Sensors API together with the Recording API. 

But that works if YOUR app produces the data. If you depend on another app, then you depend on what the other app does.

More in general: the purpose of this plugin is to merge Google Fit and HealthKit into a common API, not to expose the whole Google Fitness API within cordova. The idea is to stick to the minimum common denominator.

Both platforms allow callbacks when data is updated, see issue #94, which I am keen to integrate. Be aware that this does not assure frequent update anyhow, the frequency depends on when the data is saved in any case.

So to answer your issue:

1. what you propose does not solve your problem of frequent updates if you are not controlling how the data is generated
2. if you control how the data is generated, then you could use the SensorAPI, but I am not very keen to integrate it into this plugin because there is no HK equivalent AFAIK
3. thanks for offer, but I am super busy in this period and cannot commit. If you want to try extending this plugin, you are very welcome to send a PR.

Hope this helps.

**Comment by alindzon** [comment]
Thanks for getting back to me.

I am kind of surprised no one seems to be using that API from cordova at all.

Seems like the only way to talk to sensors in real time.

It is too bad we cannot tell Fit and Health to update more frequently i.e. take control of how often they at least try and get new data.  If we could do that it would solve the problem.




Warmest Regards,

Andrew Lindzon
647-388-3095

**Comment by dariosalvi78** [comment]
You can get data from sensors using other APIs and plugins (I have one for steps for example, see my repos).

BTW; I've discovered that the HKObserverQuery does not provide data in real time, so your objective is simply undoable in iOS using HK.

I'll close this issue, as this is not achievable in a meaningful way with this plugin.
