### ISSUE TITLE
calories.active [ android ] 

### ISSUE THREAD

**Issue by fdmartins** [dariosalvi78/cordova-plugin-health#216]
Hi, there is a little confusion and a bug in android / healthy.js

datatype calories.active not exists for android, this is calculed using basal calories and total calories. So, you need request permission for 'calories.basal' and  'calories'... and **NOT** for 'calories.active' (you need use a conditional for ios version..)

for queryAggregated you can use 'calories.active' for both OS versions.

In healthy.js you need insert retval = retval[0]; near line 99, check code below:

navigator.health.queryAggregated(opts, function(retval){
  //and remove the basal
  **retval = retval[0]; // << INSERT THIS LINE**
  
  retval.value -= basal_ms * (retval.endDate.getTime() - retval.startDate.getTime());
  //although it shouldn't happen....
  if(retval.value <0) retval.value = 0;
  onSuccess(retval);

@dariosalvi78 thank you for this plugin!

_Originally posted by @fdmartins in https://github.com/dariosalvi78/cordova-plugin-health/issues/194#issuecomment-850661314_

**Comment by juanico18** [comment]
@fdmartins That fix is not valid.
https://github.com/dariosalvi78/cordova-plugin-health/issues/295 
You have an array as result because you added in the params the attribute:
 bucket: 'day' So you need to iterate.
 
 Adittionaly take into account that basal_ms can be 0 if the user have not changed age or height during the last year.
