### ISSUE TITLE
Confilcit with the onesignal plugin

### ISSUE THREAD

**Issue by iAdil** [dariosalvi78/cordova-plugin-health#27]
Plugin url: https://github.com/OneSignal/OneSignal-Cordova-SDK/

Attaching log:
[build.txt](https://github.com/dariosalvi78/cordova-plugin-health/files/639390/build.txt)

I cant remove this plugin, so hope for your help

**Comment by dariosalviwork** [comment]
doesn't seem to be related to this plugin. Better seaching online (for example [here](http://stackoverflow.com/questions/35890257/android-errorexecution-failed-for-task-apptransformclasseswithdexforrelease)).

**Comment by dariosalviwork** [comment]
I have lessened the constraint on the fitness API version, that might help too. At the moment (8/12/2016) [the latest version of the API is 9.8.0](https://developers.google.com/fit/android/get-started)

**Comment by jkasten2** [comment]
@dariosalviwork Thanks for updating your plugin for this. We (OneSignal) opted to use a full `+` to be compatible with as many other plugins as possible.
https://github.com/OneSignal/OneSignal-Cordova-SDK/blob/2.0.10/plugin.xml#L30-L33

**Comment by dariosalviwork** [comment]
Unfortunately there is not straight forward solution to this, your "full plus" has an effect too, because it uses the latest available version while other plugins may use lower versions of the APIs (like in this case).
The solution would be that everybody agree on a version (for example the latest), but that's quite unfeasible.

I have decided to use the full plus too, but I'll add a note in the README about possible issues.

**Comment by iAdil** [comment]
But, why i cant user the older versions of plugins?
I built my app earlier with that config without any problems

**Comment by dariosalviwork** [comment]
have a read [here](https://github.com/dariosalvi78/cordova-plugin-health/blob/master/README.md#requirements-for-android-apps)
