### ISSUE TITLE
Is there a way to check if it has been authorized?

### ISSUE THREAD

**Issue by chanphillip** [dariosalvi78/cordova-plugin-health#29]
I want to implement the setting page which can show if Google fit is connected. As I observed from other apps on iOS, it seems it is not possible on iOS right?
But for Google Fit, since requestAuthorization prompts the user if it has not been authorized, is there a way to know that without prompting the user?

**Comment by dariosalvi78** [comment]
In iOS, as you say, there is no way for knowing if the app is linked with HealthKit.
In Android, the only way to know if the app was authorised previously, is by making a simple query and see if it fails. Another option would be doing the request once and then storing the result somewhere.
Let me know if this solves it.

**Comment by chanphillip** [comment]
@dariosalvi78 I tried the same trick as you said by making a query, the problem is requestAuthorization() is still needed before doing the query...
So what I'm now doing is that at the first time it is being authorized, it stores a flag. The limitation is that if the user disconnected the app with Fit, the app cannot know.

**Comment by dariosalvi78** [comment]
you'r right. Actually in iOS there is a way to ask if the app has access to a certain data type now that I think of it (although it's slightly different from asking if the app is "connected" to HealthKit). The problem is that in Fit the only way to know it is by actually making a query.

So, there is a way to implement a kind of "isAuthorized()" function, but it needs some work to be done, especially for Fit. I will create an issue, but I won't work on it soon.
I'll be happy to receive pull requests though!
