### ISSUE TITLE
iOS - Blood Glucose though entered in mg/dL, it is provided in mmol/l by plugin 

### ISSUE THREAD

**Issue by ChandraKAV** [dariosalvi78/cordova-plugin-health#292]
Health App allows user to enter blood glucose value in mg/dL, but it is always coming back converted to mmol/L, though conversion is done correctly. 

For Example, in Health app, if 87 mg/dL is entered, it comes back as 4.83 mmol/L from the plugin. 

Is it possible to fetch the value in the same units as it is entered?

**Comment by dariosalvi78** [comment]
It is the intention of this plugin to proide a common API for both Android and iOS. On Android, Google Fit does not provide unit conversion, therefore I do not want to inluce that as a feature because it would only work on iOS.

You can either do the conversion yourself (it's a multiplication), or use the underlying Telerik's plugin, from which this project is forked.
