### ISSUE TITLE
【android】 Please tell me how to exclude manual input from users.

### ISSUE THREAD

**Issue by tysucd** [dariosalvi78/cordova-plugin-health#305]
When getting the steps in android, is there a way to distinguish between the steps taken by the user manually input and the steps taken by the sensor?
The "entryMethod" is "unknown" for both.

**Comment by dariosalvi78** [comment]
What app are you using to record the data?

If it says "unknown" it's likely because the app that wrote the data didn't specify it (unless there's a bug). In that case I think that it's relatively safe to assume that those are not manually inserted values, but you cannot be 100% sure.

**Comment by dariosalvi78** [comment]
the entry method is an enum, see https://github.com/dariosalvi78/cordova-plugin-health/blob/6c8d6d2baff09b4ad08a21f87ce6af9ca6ba36be/src/android/HealthPlugin.java#L426
so it's really hard to have that wrong on the plugin side.

If Google Fit records it as "unknown" there is not much we can do unfortunately. It's a bit disappointing that Google themselves do not implement their API to full extent.

I am closing the issue because it's not really a bug, but If I get to know more, or if you discover anything more, please let's keep commenting down here, it's useful to know for everybody.

**Comment by dariosalvi78** [comment]
for reference: here's the documentation on HC: https://developer.android.com/reference/kotlin/androidx/health/connect/client/records/metadata/Metadata#recordingMethod()

**Comment by tysucd** [comment]
Thanks for creating such a great plugin.
 I will try to implement a simple pedometer in my own app using the step counter sensor.

I am very disappointed that Google has not implement an app that is fully compatible with api.

 If I find any new information I will share it too.
