### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by asivaneswaran** [dariosalvi78/cordova-plugin-health#337]
There might be an issue with Google HEalth Connect:
https://developer.android.com/health-and-fitness/guides/health-connect/plan/data-types#time-and-zone-setting

Because Google will interept the timezone has the user's timezone an the plugin sends it in UTC, there might be an issue no?

We should be able to put our own timezones of the user according to the Android docs

**Comment by asivaneswaran** [comment]
I re-opened it as I thought it was not an issue but it actually is and here is why:

Let's say I am in EDT (-4). I try to get all the activities for the day.

I send the date in the timezone of EDT, the plugin converts it to UTC. On Android, it reads that time as UTC, but it should be read as EDT, so I am not getting the right data here.

**Comment by dariosalvi78** [comment]
This is a good point and not one of easy solution (for now). The main issue is because the standard Javascript Date does not include the timezone information. In fact, the plugin converts all JS Dates into a Unix timestamps with [this function](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#ofEpochMilli-long-) and does not specify any timezone when storing data (timezone is left as null). On the way back (when querying), the conversion [is the opposite](https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#toEpochMilli--).

If I understand your link correctly, when not specified, the time zone of the saved record is assumed to be the one set currently on the operating system. So, unless you want to save a datapoint with a different timezone than the one the phone is set to, this should not really be a problem. In fact, after storing a data point it comes back with the same time.

In the future, we should use the new [Temporal API](https://2ality.com/2021/06/temporal-api.html), which supports timezones explicitly. [This article](https://docs.timetime.in/blog/js-dates-finally-fixed/) explains very well why keeping track of the time zone is a good idea.

**Comment by asivaneswaran** [comment]
Ahh that might be it, I was travelling while working and the times seemed off. I didn't click on the spot but it makes sense now.

Thanks!
