### ISSUE TITLE
Using obfuscated API Field.zzn() in Android

### ISSUE THREAD

**Issue by dzolnai** [dariosalvi78/cordova-plugin-health#7]
The Android source is using an undocumented and obfuscated, but publicly accessible method, called `Field.zzn(...)`. The problem with this, that because it is obfuscated, it can change anytime.
In my source version it is already called `Field.zzl(...)`, so the plugin does not work out of the box for Android.

**Comment by dariosalvi78** [comment]
you're right, I'll look into it...

**Comment by dzolnai** [comment]
The sample in the reference documentation does not work, it uses a method which does not exist in the SDK (`getFields(int n)`).
However, there's another way to do it, you can get the Field object from the custom datatype: http://stackoverflow.com/a/27959048/1395437

I'll try to create a pull in the coming days to fix this issue.

**Comment by dariosalvi78** [comment]
the official documentation explains how to create new data types:
https://developers.google.com/fit/android/data-types#custom_data_types

my code didn't follow it 100% because I wanted to have a declaration of the Fields somewhere statically as a reference, but there was no way for creating them (no constructor). Maybe the API has changed now, otherwise we can just follow the official documentation and forget about having the fields declared statically.
If you can propose a Pull request, then I would be very happy.

**Comment by dariosalvi78** [comment]
OK should be fixed now..

**Comment by dzolnai** [comment]
Thanks, you were faster than me :)
