### ISSUE TITLE
Support for "exercise minutes"?

### ISSUE THREAD

**Issue by rewilli5** [dariosalvi78/cordova-plugin-health#70]
For the 'activity' data type, is there a way to get the total exercise minutes for that day (instead of possibly finding the sum of the duration of all possible activities)?

**Comment by dariosalvi78** [comment]
related to #41
it's on my TODO list, but needs some work to be done. Of course any collaboration in this regard is very welcome.

**Comment by dariosalviwork** [comment]
solved by https://github.com/dariosalvi78/cordova-plugin-health/pull/92

**Comment by bryantee** [comment]
@rewilli5 - summing works for me, but `duration` only seems to be available on android. How else can you get duration for iOS?

**Comment by dariosalvi78** [comment]
duration should work in iOS too in principle

**Comment by bryantee** [comment]
Is there a particular datatype I need permission for? I'm query aggregating on activity and getting an empty object for value.

**Comment by dariosalvi78** [comment]
all data types should be asked for when you request access to activity. You can try with requesting access to distance just in case.

**Comment by bryantee** [comment]
@dariosalvi78 I believe I'm requesting all necessary data types when authorizing.

```javascript
const dataTypes = ['steps', 'distance', 'activity', 'workouts', 'calories.active', 'calories.basal', 'calories', 'height', 'weight', 'fat_percentage', 'nutrition.water', 'heart_rate'];
```

On Android, the query is working great, getting back `duration`, `distance` and `calories` when querying activity.

On iOS, I'm getting back and empty `value` property.

Is there any glaring omission I might be making?

**Comment by bryantee** [comment]
Ok, I got it working. Just need to query for `HKQuantityTypeIdentifierAppleExerciseTime`.

I'll get up a pull request sometime soon.

**Comment by dariosalviwork** [comment]
I am a bit confused now, I can see you are mentioning three separate issues:

1. the plugin returning empty values. This shouldn't happen in the query() function, but it may happen in the queryAggregated(), because you may just have no activities within a certain bucket. That's OK and you can simply check if your value exists or not within a certain bucket.

2. the workout not returning a duration. This is up to the app that writes the duration. If you check the [HKWorkout type](https://developer.apple.com/documentation/healthkit/hkworkout), you can see that you can associate energy, distance and duration to a workout, but they are not mandatory. If you don't have a duration, remember that you also have the start and end timestamps that you can use as a proxy.

3. you want to retrieve the Apple Exercise Time. That's something different than the duration in my understanding and it is not supported by this plugin. I would be happy to merge a PR if you want to include it. You may want to add it as a separate data type (call it "appleExerciseTime" or something similar).
From the documentation of the workout, it doesn't seem that the Apple exercise time is associated to a workout, so you probably need to query it separately.

**Comment by bryantee** [comment]
@dariosalviwork 

Sorry about the confusion. You're absolutely right on the empty values. I was doing an aggregate on `activity` to get back `duration`, which does actually work as expected. My (incorrect) assumption was that the any activity, including walking, would come back with an associated duration.

As for the Exercise Time, that's what I'm after and I did get it working with the plugin once the correct TypeIdentifier was added. I like going with "appleExerciseTime" as it's very descriptive and is clear it only works with HealthKit.
