### ISSUE TITLE
Make HKCategoryTypeIdentifierSleepAnalysis optional addition if activity type picked on ios

### ISSUE THREAD

**Issue by petemcwilliams** [dariosalvi78/cordova-plugin-health#73]
Is it possible to either split sleep and activity as separate types or to make addition of HKCategoryTypeIdentifierSleepAnalysis to activity type optional.

Wanting to get activities and sleep is not relevant to the application I am creating so would rather not have to ask for that permission.

**Comment by dariosalviwork** [comment]
The reason why sleep is there is because Google Fit provides it.
The intention of this plugin is to merge the APIs as much as possible, so I believe that sleep should be returned by the plugin.
You can still filter sleep out in the application.

I'll close this issue, but I'll be happy to accept a PR that does something like this (only of iOS):
```
navigator.health.requestAuthorization(['workouts'], successCallback, errorCallback)
```

this requests auth only for workout and excludes sleep.

Then, in the query:

```
navigator.health.query({
  startDate: new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000),
  endDate: new Date(), // now
  dataType: 'activity',
  includeSleep: false
}, successCallback, errorCallback)
```

It's all very simple to do, check [health.js](https://github.com/dariosalvi78/cordova-plugin-health/blob/master/www/ios/health.js)

**Comment by dariosalviwork** [comment]
OK I'll leave it open, I see that there may be more people interested into this feature.

**Comment by dariosalvi78** [comment]
all right, it was so simple that I decided to fix it.
Now simply request authorisation or query "workouts" (but only available in iOS !)

**Comment by dariosalviwork** [comment]
I've added support in the queries too, forgot to do that in the last commit.
